#!/usr/bin/env python3
import sys
from paddleocr import PaddleOCR
import cv2

if len(sys.argv) != 2:
    sys.exit(1)

img_path = sys.argv[1]
ocr = PaddleOCR(use_angle_cls=False, lang='en')
result = ocr.ocr(img_path, cls=False)

if not result:
    sys.exit(1)

# junta todos os textos e pega os primeiros 4 chars
text = "".join([line[1][0] for line in result])
print(text[:4])
