# .github/workflows/generate_playlist.yml
name: Playlist

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install yt-dlp
        run: pip install yt-dlp

      - name: Generate M3U playlist
        run: python generate_playlist.py

      - name: Commit and Push
        run: |
          git config user.name "youngsadsatan"
          git config user.email "114822995+youngsadsatan@users.noreply.github.com"
          git add docs/O_Estudio.m3u
          git commit -m "Update Playlist"
          git push
