name: EroMe Bulk Register

on:
  workflow_dispatch:

jobs:
  signup:
    runs-on: ubuntu-latest
    env:
      SITE_URL: https://www.erome.com/user/register
      USERNAME: ${{ secrets.SECRET_USER }}
      PASSWORD: ${{ secrets.SECRET_PASS }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python and install OCR deps
        run: |
          python3 -m pip install --upgrade pip
          pip install paddleocr "paddlepaddle>=3.1.0" shapely

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Node deps
        run: npm install

      - name: Run bulk register
        run: node account.js

      - name: Upload log
        uses: actions/upload-artifact@v4
        with:
          name: erome-register-log
          path: ./register.log
